catalogMode: prefer
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - chapters/*
  - packages/*
  - playground/*

catalog:
  "@antfu/eslint-config": ^7.2.0
  "@types/node": 20.19.8
  eslint: ^9.39.2
  ts-node: 10.9.2
  typescript: 5.8.3
